apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app-service
spec:
  selector:
    app: devops-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
